<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="LogIn Test"
           tests="6"
           failures="1"
           errors="0"
           skipped="0"
           time="33.278">
  <properties />
            <testcase name="checkLinksInCreateAccount" time="2.124" classname="com.ugapp.testcases.TC_04_CreateAccountTest">
                <failure type="java.lang.AssertionError"
                  message="expected [] but found [866-277-6589]"
              >
<![CDATA[java.lang.AssertionError: expected [] but found [866-277-6589]
  org.testng.Assert.fail(Assert.java:93)
  org.testng.Assert.failNotEquals(Assert.java:512)
  org.testng.Assert.assertEqualsImpl(Assert.java:134)
  org.testng.Assert.assertEquals(Assert.java:115)
  org.testng.Assert.assertEquals(Assert.java:189)
  org.testng.Assert.assertEquals(Assert.java:199)
  com.ugapp.pages.CreateAccountPage.checkAndValidateEnrollmentSupportPhone(CreateAccountPage.java:86)
  com.ugapp.testcases.TC_04_CreateAccountTest.checkLinksInCreateAccount(TC_04_CreateAccountTest.java:40)
  java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
  java.base/java.lang.reflect.Method.invoke(Method.java:578)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:744)
  org.testng.TestRunner.run(TestRunner.java:602)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
  org.testng.SuiteRunner.run(SuiteRunner.java:289)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
  org.testng.TestNG.runSuites(TestNG.java:1144)
  org.testng.TestNG.run(TestNG.java:1115)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="verifyCreateAcc" time="4.068" classname="com.ugapp.testcases.TC_04_CreateAccountTest" />
                <testcase name="createAccountTest" time="5.476" classname="com.ugapp.testcases.TC_04_CreateAccountTest" />
                <testcase name="createAccountTest" time="4.320" classname="com.ugapp.testcases.TC_04_CreateAccountTest" />
                <testcase name="createAccountTest" time="6.701" classname="com.ugapp.testcases.TC_04_CreateAccountTest" />
                <testcase name="createAccountTest" time="10.589" classname="com.ugapp.testcases.TC_04_CreateAccountTest" />
      
</testsuite>
